name: dicedb
version: 1.0.0
description: DiceDB database (https://dicedb.io/) client, with both simplicity and performance as primary goals.

environment:
  sdk: '>=3.5.1 <4.0.0'

dev_dependencies:
  test: ^1.25.13
